### ISSUE TITLE
wheels for polyleven

### ISSUE THREAD

**Issue by datacycling** [fujimotos/polyleven#10]
First of all thanks for making polyleven available - the performance of polyleven is unbeatable !

Would it be possible for you to add support for wheels ? 

I am using this library to build a docker image and lack of wheels is increasing the size of the image.

**Comment by fujimotos** [comment]
> First of all thanks for making polyleven available - the performance of polyleven is unbeatable !

Thank you!

> Would it be possible for you to add support for wheels ?

I'm planning to support it, but I first need to investigate how to build it. WFM.

**Comment by datacycling** [comment]
I used the workflow shown on https://github.com/pypa/cibuildwheel to build the wheels and I was able to build all the artifacts. It was a matter of adding one yml file.

You can check it out at https://github.com/datacycling/polyleven/actions

The wheels are at https://github.com/datacycling/polyleven/suites/8529941557/artifacts/380409277

**Comment by fujimotos** [comment]
@datacycling I released polyleven v0.8 with wheel support.
For details, please visit PyPI's package page:

https://pypi.org/project/polyleven/#files

**Comment by datacycling** [comment]
Thanks a lot @fujimotos for taking care of it so quickly !!
