### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by MiWeiss** [fujimotos/polyleven#8]
While I was able to install polyleven on python 3.6 - 3.9, installation did not succeed for python 3.10. 

Thanks for providing polyleven - it's great!

**Comment by MiWeiss** [comment]
Actually, it seems that installing locally `python setup.py install` works, but `pip install polyleven` does not.

Might thus very well be a problem with my pip installation, or smth like that. Please do not hesitate to close the issue if you cannot reproduce the error.

**Comment by fujimotos** [comment]
> installation did not succeed for python 3.10.

I spent some time today trying to reproduce this issue using
Debian sid. The tested version of Python was v3.10.4, and
it worked (the detailed log attached below).

The Debian machine was a clean environment (i.e. built from
scratch for the testing), so I believe the installation should work
on other environments.

```python3
$ sudo apt install -y python3-pip
$ pip install polyleven                                                       
Collecting polyleven                                                                                 
  Downloading polyleven-0.7.tar.gz (5.1 kB)                                                          
  Preparing metadata (setup.py) ... done                                                             
Building wheels for collected packages: polyleven                                                    
  Building wheel for polyleven (setup.py) ... done                                                   
  Created wheel for polyleven: filename=polyleven-0.7-cp310-cp310-linux_x86_64.whl size=17587 sha256=
22547cba66b0e0b57f9b7ef1fa66ca5b711d5fe9f5c763f131578438893981c5                                     
  Stored in directory: /root/.cache/pip/wheels/15/10/49/773b49872072ac4c547856b4d389a63165a7bcf9cbbe5
541f0                                                                                                
Successfully built polyleven                                                                         
Installing collected packages: polyleven                                                             
Successfully installed polyleven-0.7  
$ python3
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import polyleven
>>> polyleven.levenshtein("abc", "aaa")
2
```

**Comment by fujimotos** [comment]
@MiWeiss If you can describe the system info (Linux ? macOS? etc.)
where installation failed, I think I can investigate your issue a bit more.

One idea I'm thinking is to prepare a wheel package for polyleven,
so that `pip install polyleven` just works.

**Comment by MiWeiss** [comment]
As assumed, it was probably a problem with my local installation. Not problems appeared later that day with other libraries :-)

Sorry for the time wasted...
